# Офферы
## Получить список офферов
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json

###

## Добавить новыЙ оффер
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3Y2ExMTIzMzhkYWZhMzhlMjZhNWNlZSIsIm5hbWUiOiJKYWNrIiwiZW1haWwiOiJ0b3JhbnNAbWFpbC5uZXQiLCJpYXQiOjE3NDE3MTYwNTUsImV4cCI6MTc0MTg4ODg1NX0.JgBoPolDnWz89wDq8LrgMKCpbkK_btqtzYF_OJxHcWo

{
  "title": "Nice, cozy, warm big bed apartment",
  "description": "Design interior in most sympathetic area!",
  "createdDate": "2025-01-01",
  "city": "Paris",
  "previewImage": "preview.jpg",
  "images": [
    "image-1.jpg",
    "image-2.jpg",
    "image-3.jpg",
    "image-4.jpg",
    "image-5.jpg",
    "image-6.jpg"
    ],
  "isPremium": true,
  "rating": 4,
  "type": "House",
  "bedrooms": 2,
  "maxAdults": 6,
  "price": 1560,
  "goods": ["Breakfast", "Air conditioning"],
  "userId": "67bfaf67982ac03877fe3f38",
  "commentCount": 7,
  "location": {
    "latitude": 48.85661,
    "longitude": 2.351499
  }
}

###

# Получить оффер по идентификатору
GET http://localhost:5000/offers/67c8574867d9cca16d9cdc88 HTTP/1.1

###

## Удалить оффер по идентификатору
DELETE http://localhost:5000/offers/67bfaf67982ac03877fe3f4c HTTP/1.1

###

## Обновить оффер по идентификатору
PATCH http://localhost:5000/offers/67d080df33828e37fc7d1538 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3Y2ExMTIzMzhkYWZhMzhlMjZhNWNlZSIsIm5hbWUiOiJKYWNrIiwiZW1haWwiOiJ0b3JhbnNAbWFpbC5uZXQiLCJpYXQiOjE3NDE3MTYwNTUsImV4cCI6MTc0MTg4ODg1NX0.JgBoPolDnWz89wDq8LrgMKCpbkK_btqtzYF_OJxHcWo

{
  "title": "New amazing city",
  "description": "New amazing description",
  "price": 1700,
  "isFavorite": false
}

###

## Список комментариев к офферу
GET http://localhost:5000/offers/67c8574867d9cca16d9cdc88/comments HTTP/1.1

###

## Получить список Премиум офферов
GET http://localhost:5000/offers/brussels/premium HTTP/1.1
Content-Type: application/json

###

## Получить список Избранных офферов
GET http://localhost:5000/offers/favorites HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjY3Y2ExMTIzMzhkYWZhMzhlMjZhNWNlZSIsIm5hbWUiOiJKYWNrIiwiZW1haWwiOiJ0b3JhbnNAbWFpbC5uZXQiLCJpYXQiOjE3NDE3MTYwNTUsImV4cCI6MTc0MTg4ODg1NX0.JgBoPolDnWz89wDq8LrgMKCpbkK_btqtzYF_OJxHcWo

###
