# Офферы
## Получить список всех офферов
GET http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
# Authorization: Bearer *

###

## Получить ограниченный список из двух офферов
GET http://localhost:5000/offers?count=2 HTTP/1.1
Content-Type: application/json
# Authorization: Bearer *

###

## Добавить новыЙ оффер
POST http://localhost:5000/offers HTTP/1.1
Content-Type: application/json
# Authorization: Bearer *

{
  "title": "Appartment in the center of Paris",
  "description": "Design interior in most sympathetic area!",
  "city": { "name": "Paris" },
  "previewImage": "preview.jpg",
  "images": [
    "image-1.jpg",
    "image-2.jpg",
    "image-3.jpg",
    "image-4.jpg",
    "image-5.jpg",
    "image-6.jpg"
    ],
  "isPremium": true,
  "type": "house",
  "bedrooms": 4,
  "maxAdults": 7,
  "price": 10000,
  "goods": ["Air conditioning", "Breakfast"],
  "location": {
    "latitude": 48.85231,
    "longitude": 2.356232
  }
}

###

# Получить оффер по идентификатору
GET http://localhost:5000/offers/67f15f4c0350a40b2b363d58 HTTP/1.1
# Authorization: Bearer *

###

## Удалить оффер по идентификатору
DELETE http://localhost:5000/offers/67e2981b2641d485167934c3 HTTP/1.1
# Authorization: Bearer *

## Обновить оффер по идентификатору
PATCH http://localhost:5000/offers/67f15f4c0350a40b2b363d58 HTTP/1.1
Content-Type: application/json
# Authorization: Bearer *

{
  "title": "New amazing appartment",
  "description": "New amazing appartment nearby!",
  "city": { "name": "Cologne" },
  "price": 7000
}

###

## Получить список премиум офферов по выбранному городу
GET http://localhost:5000/offers/premium?city=Paris HTTP/1.1
Content-Type: application/json
# Authorization: Bearer *

###
