export const Component = {
  RestApplication: Symbol(),
  Logger: Symbol(),
  Config: Symbol(),
  DatabaseClient: Symbol(),
  UserService: Symbol(),
  UserModel: Symbol(),
  OfferService: Symbol(),
  OfferModel: Symbol(),
  CommentService: Symbol(),
  CommentModel: Symbol(),
  OfferController: Symbol(),
  ExceptionFilter: Symbol(),
  UserController: Symbol(),
} as const;
