# Комментарии
## Получить список комментариев по идентификатору оффера
GET http://localhost:5000/comments/67f15f4c0350a40b2b363d58 HTTP/1.1
Content-Type: application/json
# Authorization: Bearer *


###

## Создать комментарий по идентификатору оффера
POST http://localhost:5000/comments/67f15f4c0350a40b2b363d58 HTTP/1.1
Content-Type: application/json
# Authorization: Bearer *

{
  "comment": "New amazing comment",
  "rating": 5
}

###
